### ISSUE TITLE
Add Python `isort` to `pre-commit`

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#295]

**Comment by jbampton** [comment]
Blocked:

```
Salam$ make check
pre-commit install
pre-commit installed at .git/hooks/pre-commit
pre-commit run --all-files
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/abe/.cache/pre-commit/repoh4gmipbo/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/abe/.cache/pre-commit/repoh4gmipbo
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/abe/.cache/pre-commit/repoh4gmipbo/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/abe/.cache/pre-commit/repoh4gmipbo/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/abe/.cache/pre-commit/repoh4gmipbo/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-l8ukuwi1/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-l8ukuwi1/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 60, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - data.extras.pipfile_deprecated_finder[2] must match pattern ^[a-zA-Z-_.0-9]+$
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at /home/abe/.cache/pre-commit/pre-commit.log
make: *** [Makefile:3: check] Error 3
```

Similar error message here:

https://github.com/zylon-ai/private-gpt/issues/942

**Comment by BDadmehr0** [comment]
https://github.com/SalamLang/Salam/pull/297

**Comment by BDadmehr0** [comment]
The PR related to this issue has been closed. Is there a reason or problem why the issue itself hasn’t been closed? @jbampton

**Comment by jbampton** [comment]
I was not feeling 100% this last week so took some time off.

Sorry for the delay @BDadmehr0 

Let us all go turbo on Salam going forwards :100:
