### ISSUE TITLE
pre-commit utf8 supporting

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam#408]
> pre-commit run --all-files

```
run yamllint.............................................................Failed
- hook id: yamllint
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\cli.py", line 223, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\linter.py", line 232, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 811: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\cli.py", line 223, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\linter.py", line 232, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 506: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\cli.py", line 223, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\linter.py", line 232, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 462: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\cli.py", line 223, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\linter.py", line 232, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4251: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\cli.py", line 223, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\linter.py", line 232, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 561: character maps to <undefined>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Scripts\yamllint.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\cli.py", line 223, in run
    problems = linter.run(f, conf, filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\.cache\pre-commit\repor_unaq9p\py_env-python3\Lib\site-packages\yamllint\linter.py", line 232, in run
    content = input.read()
              ^^^^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 375: character maps to <undefined>
```

**Comment by BaseMax** [comment]
## Configure Default Encoding for Python (Not Recommended)

You can change the default system encoding, but it's generally not recommended to do this in practice because it can affect other Python code in unexpected ways. However, if you're working in a controlled environment, you can modify the default encoding to UTF-8 in the Python interpreter.

```python
import sys
sys.setdefaultencoding('utf-8')
```

**Comment by BaseMax** [comment]
```
>>> sys.getdefaultencoding()
'utf-8'
```

**Comment by jbampton** [comment]
We are no longer using pre-commit so this no longer applies.

We now use prek. Closing
